### ISSUE TITLE
Visualize the Object Pose Ground Truth

### ISSUE THREAD

**Issue by taeyeopl** [Junggy/HouseCat6D#10]
I ran the visualization code on the train/val/test set following the code `python vis_obj.py ./ scene01`.
It looks like the visualization looks wired to me. Do you have any ideas?

![scene_02](https://github.com/user-attachments/assets/72b7b154-3d07-40a2-b269-b57f7be3caa9)
![val_scene1](https://github.com/user-attachments/assets/a299703d-2999-4be3-b9ac-bd2890f61128)
![test_scene1](https://github.com/user-attachments/assets/00a88ecc-14af-403a-aecd-845459c9a84a)

**Comment by taeyeopl** [comment]
I visualize per object, but it still has errors. Have you checked the visualization script, including pose, object models, and code?
![Screenshot from 2024-07-17 13-35-49](https://github.com/user-attachments/assets/b172e5bf-22f2-4f07-a19a-506906f02cb4)

**Comment by Junggy** [comment]
Hi!

sorry for the late response!
both me and my other colleague are doing intern at the moment that it takes some time to respond..

So i tried to download subset of the scene (val1, val2) in the new machine and then ran the script that is directly cloned from this repo. (btw, prior to cloning, I fixed one bug related to the file directory - but this shouldnt cause that rotational issue tho)

I see that I works fine as far as I see. 

![val_scene_01](https://github.com/user-attachments/assets/2cc6cd11-0919-4f70-baac-98219b2fcd78)

I am wondring - did you change anything in the vis code or dataset itself?
It rather feels like your code is not reading the correct bounding box size per object.
They seem to be oriented correctly but bounding box sizes seem to be mixed up with other objects.

could you try to clone the repo again / and also redownload subset (like val1-val2, the lightest ones) and try again?

if you still have an issue, please let me know!

**Comment by taeyeopl** [comment]
Thanks for the reply. @Junggy, I haven't changed any codes. I have tried again (clone the repo and redownload the dataset), but it still has some issues. I feel like the version makes an issue. Could you also share your reqirement.txt version? https://github.com/Junggy/HouseCat6D/blob/main/requirement.txt

**Comment by Junggy** [comment]
Hmmm thats very strange.
actually mask is rendered from pyrender and trimesh, which I see they are working fine.
while the other part is rendered via label pickles and functions I borrowed from other repo (see reference in the code)

I assume something is wrong in the later part. (label and functions), but its really strange ..

anyhow, the new machine I tested on last week, I installed modules with the following version. (python 3.12.4)

opencv-python 4.10.0.84
numpy 1.26.4
pyrender 0.1.45
trimesh 4.4.1

the rest from requirements is either python standard that I cannot check the version from pip list or
not really required for vis_obj.py

Let me know whether the problem is solved by installing the same version!

**Comment by taeyeopl** [comment]
Thanks, @Junggy. It still doesn't work for me. Do you download the dataset directory in the same way as the one below for the new machine? 

wget http://www.campar.in.tum.de/public_datasets/2023_housecat6d_new/val_scene.zip
wget http://www.campar.in.tum.de/public_datasets/2023_housecat6d_new/obj_models.zip

**Comment by Junggy** [comment]
ah sorry for the late reply
@taeyeopl I just downloaded from windows 10 machine by clicking the link.

All the data and codes are downloaded from new pc to test out.
are you still having issue?

**Comment by Junnn-create** [comment]
@taeyeopl @Junggy I have the same problem. Is there an update?

**Comment by Junggy** [comment]
Its very late but,
Actually, I figured this was an issue with my python dictionary's sorting criteria, which was os dependent ...
adding sorting on the for loop for objects solved issue from my side. I updated the source code for vis
